[package]
name = "advent_of_code_2021_rs"
version = "0.1.0"
edition = "2021"
# 1822588-20211204-93e9ef75

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
